### ISSUE TITLE
trying to get this to work...

### ISSUE THREAD

**Issue by renfieldk** [scottdermott/cordova-plugin-discovery#1]
Thanks for this plugin!
I'm trying to get it to discover mDNS discoverable service using the sensible framework from mono.hm (http://sensible.mono.hm)
Basically this broadcasts via mDNS a service available as "_sensible._tcp" so I'm not sure what kind of servicetype to use. I tried "zeroconf:_sensible._tcp", and "zeroconf:all" but I could not discover the sensible service.
Is this plugin simply not compatible, or do I need to use a different servicetype?
Thanks again!

**Comment by scottdermott** [comment]
Hi renfieldk,

mDNS & ZeroConf are slightly different to SSDP / UPnP discovery.
Have a look at https://github.com/vstirbu/ZeroConf

Thanks :-)

**Comment by renfieldk** [comment]
Awesome thanks!

Regards,

r e n

{ "footer" : { "phone": "+81.90.8875.8632" } }
