### ISSUE TITLE
Consider adding a package.json

### ISSUE THREAD

**Issue by MPvI** [scottdermott/cordova-plugin-discovery#10]
When using:
`cordova plugin add ..\..\cordova-plugin-discovery\`
I get:
`Error: Invalid Plugin! ..\..\cordova-plugin-discovery needs a valid package.json`

I added this package.json 
`{
  "name": "cordova-plugin-discovery",
  "version": "0.2.0",
  "description": "Simple plugin to get any SSDP / UPnP / DLNA service on a local network",
  "cordova": {
    "id": "com.scott.serviceDiscovery",
    "platforms": [
      "android",
      "ios"
    ]
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/scottdermott/cordova-plugin-discovery.git"
  },
  "keywords": [
    "ecosystem:cordova",
    "cordova-android",
    "cordova-ios"
  ],
  "engines": [
    {
      "name": "cordova",
      "version": ">=3.4.0"
    }
  ],
  "author": "scottdermott",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/scottdermott/cordova-plugin-discovery/issues"
  },
  "homepage": "https://github.com/scottdermott/cordova-plugin-discovery#readme"
}`
via 
`plugman createpackagejson /path/to/plugin`.

Please consider adding this to your repo. Thanks for your plugin :)

**Comment by scottdermott** [comment]
Thanks @Ragingart, package.json file was not required by Cordova when I originally wrote this plugin. I will update.
