### ISSUE TITLE
Upnp playback

### ISSUE THREAD

**Issue by arjunmenon** [scottdermott/cordova-plugin-discovery#11]
To work over this is there a plugin you would recommend?

From the example, `console.log(devices)` return multiple hash of uuid, location, st, etc. More than 10 hashes of those.

If you could help with a flow to follow up after setting up this plugin, that would be cool.

**Comment by scottdermott** [comment]
@arjunmenon I have written a pretty comprehensive JS stack for DLNA, but that is locked down under the company i worked for copyright and distribution license.

Working on a simple stack at the moment, will let you know when i have something substantial.

**Comment by arjunmenon** [comment]
Hey
Great to know! I have this basic code to get, list and call actions - https://gist.github.com/arjunmenon/8ad89f7348442834efe6271e731221f4
I haven't tested it for OpenHome. That is a primary goal.
Coded to adapt it for TabrisJS. It can work for Cordova as well.
Bit struggling on the subscription part. TabrisJS is not that friendly to work with sockets.

EDIT
If i could stir the pot, a Cordova plugin for Contentdirectory, would be so so  cool. At present, i am relying on this - https://github.com/floatinghotpot/cordova-httpd - to serve SD card music directory. Not neat. very hacky. Unsure, if it is a security gaffe.
If you can advise, can this be a "okay" alternative?

**Comment by arjunmenon** [comment]
> Working on a simple stack at the moment, will let you know when i have something substantial.

Hey any progress on this? I have most of the JS part. ContentDirectory and eventing, which require HTTP calls made to the OS directly, is not figured out. How does your end look?
