### ISSUE TITLE
FR: release the plugin on npm

### ISSUE THREAD

**Issue by mburger81** [scottdermott/cordova-plugin-discovery#12]
This plugin looks great, we would like to ask for a feature request

Can you please release the plugin on npm, I think it would be much more easier for everyone to have the plugin released over npm.

If you'll do this and if anything is working great, we would like in feature to propose to the ionic team to integrate this as ionic-native plugin. If we find the time we can open a pull request on them. What do you think about it?

**Comment by mburger81** [comment]
@scottdermott hi, can you jump into this FR?
thx

**Comment by scottdermott** [comment]
@mburger81 https://www.npmjs.com/package/cordova-plugin-discovery
`npm i cordova-plugin-discovery`
