### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token ;" in serviceDiscovery.js

### ISSUE THREAD

**Issue by JanMod** [scottdermott/cordova-plugin-discovery#13]
module.exports = {

    getNetworkServices: function (service, addConfigXML, successCallback, errorCallback) {
    	var processResponse = function (data) {
	    	successCallback(data);
	    }
    	};//"Uncaught SyntaxError: Unexpected token ;" 
        cordova.exec(processResponse, errorCallback, "serviceDiscovery", "getNetworkServices", [service]);
    }};

As soon as I start running my ionic@1-App on a Android-device the console on chrome://inspect shows an uncaught syntax error on line 8. The semicolon appears although I removed it.

**Comment by scottdermott** [comment]
Cordova Plugin not Ionic
JS Linter has no issue with the ";"

`module.exports = {
    getNetworkServices: function (service, successCallback, errorCallback) {
        var processResponse = function (data) {
            successCallback(data);
        };
        cordova.exec(processResponse, errorCallback, "serviceDiscovery", "getNetworkServices", [service]);
    }
};`
