### ISSUE TITLE
Error: Unpublished by skyup-str on 2015-12-28T12:21:38.174Z  when tried to use it in ionic

### ISSUE THREAD

**Issue by karthhic** [scottdermott/cordova-plugin-discovery#14]
I am trying to use this library in ionic,when i tried to install it is giving me this error code. I am new to Ionic and mobile application.

**Comment by JanMod** [comment]
Try 
**cordova plugin add com.scott.serviceDiscovery**


But somehow I can't use this because of the error:

> "Uncaught SyntaxError: Unexpected token ;" in serviceDiscovery.js

I would be really gratefull if you could send me a reply if it's working for you.  
Btw I'm using ionic v1.

**Comment by karthhic** [comment]
When i try to use this in home.ts
import { IonicDiscover } from 'cordova-plugin-discovery';
Cannot find module "cordova-plugin-discovery"

import { IonicDiscover } from 'com.scott.serviceDiscovery';
Cannot find module "com.scott.serviceDiscovery"

I can see it in the library list.
![screenshot from 2017-10-29 10-24-28](https://user-images.githubusercontent.com/12935323/32141861-917916b4-bc93-11e7-8e20-e470241fb1f3.png)

**Comment by karthhic** [comment]
Hi, 
I tried it in cordova after getting fed up with ionic.

Its working cool...

**Comment by scottdermott** [comment]
Won't work with ionic, it is a Cordova plugin
