### ISSUE TITLE
Auto install not working 

### ISSUE THREAD

**Issue by charlynedsson** [scottdermott/cordova-plugin-discovery#2]
Hi,

Thanks for sharing this plugin. 
I have tried to install it following your instructions but it seems that cordova auto install is not recognizing your plugin. 
Even though no error message is thrown by the cli, the plugin is not added to my project. 
Could it be due to the config.xls ?

**Comment by scottdermott** [comment]
Thanks @unihockey, I have updated the readme;

Installing the plugin has changed from ""cordova plugin install../cordova-plugin-discovery" to 
"cordova plugin add ../cordova-plugin-discovery"

**Comment by charlynedsson** [comment]
Awesome, I should have been more careful. I'll try it out this evening. Have a good day.
