### ISSUE TITLE
Build failure for Cordova 6.0.0

### ISSUE THREAD

**Issue by PauLL54** [scottdermott/cordova-plugin-discovery#3]
When compiling the Cordova project with CLI version 6.0.0, the build failed:
"package org.apache.http does not exist".

The reason seems to be that the apache packages are deprecated.
Is there a way to still use the apache packages?

**Comment by nbdamian** [comment]
You should be able to add the following to your build.gradle:

```
android {
......
    useLibrary 'org.apache.http.legacy'
}
```

**Comment by gentunian** [comment]
Which file should we use?

```
./platforms/android/CordovaLib/build.gradle
./platforms/android/build.gradle
```

Will this be rewritten in order to not use a deprectaed library?

Best,

**Comment by nbdamian** [comment]
Use `./platforms/android/build.gradle`
