### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by ScottDodsonDev** [scottdermott/cordova-plugin-discovery#9]
I can't get this to work on Android or iOS. I can see that the M-SEARCH request is being made by using Wireshark but I never get an OK from any device. I receive a response with a list of devices but I believe these are just the devices that send out NOTIFY. I'm using the code in the example.

**Comment by scottdermott** [comment]
Hi, 'a list of devices' is the expected behaviour. This is only a (SSDP) discovery plugin.
Once you have the list of devices, you can communicative over the DLNA HTTP API to query, control etc
